# Generated by Django 4.2.6 on 2023-10-31 17:55

import RecipesApp.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RecipesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('description', models.TextField(max_length=512, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to=RecipesApp.models.upload_path_recipe, verbose_name='Изображение')),
                ('cooking_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время приготовления')),
                ('step', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество шагов')),
                ('like', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Like')),
                ('dislike', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dislike')),
                ('created_at', models.DateTimeField(verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Выводить?')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(to='RecipesApp.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecipesApp.recipe')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='CookingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=32, verbose_name='Шаг')),
                ('description', models.TextField(max_length=512, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to=RecipesApp.models.upload_path_recipe, verbose_name='Изображение')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooking_step', to='RecipesApp.recipe')),
            ],
            options={
                'verbose_name': 'Шаг рецепта',
                'verbose_name_plural': 'Шаги рецепта',
            },
        ),
    ]
