# Generated by Django 4.2.6 on 2023-10-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipesApp', '0002_recipe_ingredients_cookingstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='quantity',
            field=models.CharField(max_length=64, verbose_name='Количество'),
        ),
    ]
