# Generated by Django 4.2.6 on 2023-11-06 12:42

import RecipesApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecipesApp', '0003_alter_ingredients_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookingstep',
            name='image',
            field=models.ImageField(blank=True, upload_to=RecipesApp.models.upload_path_step_cooking, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='cookingstep',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecipesApp.recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
