# Generated by Django 4.2.6 on 2023-11-06 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecipesApp', '0005_remove_recipe_category_category_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecipesApp.recipe', verbose_name='Рецепт'),
        ),
    ]
