# Generated by Django 4.2.6 on 2023-11-11 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipesApp', '0008_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='like',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient_quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество ингредиентов'),
            preserve_default=False,
        ),
    ]
