# Generated by Django 4.2.6 on 2023-11-11 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipesApp', '0009_remove_recipe_dislike_remove_recipe_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredient_quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество ингредиентов'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='step',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество шагов'),
        ),
    ]
